const vscode = require('vscode');

module.exports = function (context) {
    // 注册关键词
    context.subscriptions.push(vscode.languages.registerCompletionItemProvider('css', {
        provideCompletionItems(document, position) {
            const linePrefix = document.lineAt(position).text.substr(0, position.character);
            if (!linePrefix.endsWith('Q')) {
                return undefined;
            }

            return [
                new vscode.CompletionItem('QAbstractButton', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QAbstractItemView', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QAbstractScrollArea', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QAbstractSlider', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QAbstractSpinBox', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QCalendarWidget', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QCheckBox', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QColorDialog', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QColumnView', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QComboBox', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QCommandLinkButton', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QDateEdit', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QDateTimeEdit', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QDial', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QDialog', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QDialogButtonBox', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QDockWidget', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QDoubleSpinBox', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QErrorMessage', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QFileDialog', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QFocusFrame', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QFontComboBox', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QFontDialog', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QFrame', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QGraphicsView', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QGroupBox', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QHeaderView', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QInputDialog', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QKeySequenceEdit', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QLCDNumber', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QLabel', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QLineEdit', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QListView', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QListWidget', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QMainWindow', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QMdiArea', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QMdiSubWindow', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QMenu', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QMenuBar', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QMessageBox', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QOpenGLWidget', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QPlainTextEdit', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QProgressBar', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QProgressDialog', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QPushButton', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QRadioButton', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QRubberBand', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QScrollArea', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QScrollBar', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QSizeGrip', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QSlider', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QSpinBox', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QSplashScreen', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QSplitter', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QSplitterHandle', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QStackedWidget', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QStatusBar', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QTabBar', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QTabWidget', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QTableView', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QTableWidget', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QTextBrowser', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QTextEdit', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QTimeEdit', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QToolBar', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QToolBox', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QToolButton', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QTreeView', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QTreeWidget', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QUndoView', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QWidget', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QWizard', vscode.CompletionItemKind.Keyword),
                new vscode.CompletionItem('QWizardPage', vscode.CompletionItemKind.Keyword),
            ];
        }
    }, 'Q'));
};